### ISSUE TITLE
Error applying a CRD generated by controller-tools that contains the ContainerPort struct

### ISSUE THREAD

**Issue by MenD32** [kubernetes-sigs/controller-tools#1027]
I have the following types.go file:

```
// types.go

type ExampleSpec struct {
	apiv1.ContainerPort `json:",inline"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.conditions[0].message"
// +kubebuilder:printcolumn:name="Synced",type="string",JSONPath=".status.conditions[0].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +genclient

type Example struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec ExampleSpec	`json:"spec"`
}
```

after generating a CRD from this code with controller-gen like so:
`controller-gen crd:generateEmbeddedObjectMeta=true paths="./pkg/apis/..." output:stdout | tail -n +2 > manifests/crd.yaml` 

and trying to apply with `kubectl create` I get the following error(s):
```
* spec.validation.openAPIV3Schema.properties[spec].properties[protocol].allOf[0].default: Forbidden: must be undefined to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[protocol].allOf[1].default: Forbidden: must be undefined to be structural
```

after some messing around i found that removing the `// +default="TCP"` comment from ContainerPort.Protocol in k8s.io/api, fixes the issue while maintaining the default value of TCP in the CRD itself.

versions:
- Kubernetes v1.30.0
- Controller-gen built from master, hash is b98a19a9c576353e1093ef2bbe4a38701029d381
- k8s.io/api@v0.30.3

**Comment by aerfio** [comment]
It affects https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.0-beta.0, works with v0.15.0 in my case

**Comment by sbueringer** [comment]
Another case was reported here: https://github.com/kubernetes-sigs/controller-tools/issues/1034

**Comment by sbueringer** [comment]
I assume the relevant change since v0.15.0 is this one: https://github.com/kubernetes-sigs/controller-tools/pull/938

**Comment by sbueringer** [comment]
Not sure what's going on, clearly looks like a bug:

```go
	// Protocol for port. Must be UDP, TCP, or SCTP.
	// Defaults to "TCP".
	// +optional
	// +default="TCP"
	Protocol corev1.Protocol `json:"protocol,omitempty" protobuf:"bytes,4,opt,name=protocol,casttype=Protocol"`
```

leads to

```yaml
              protocol:
                allOf:
                - default: TCP
                - default: TCP
                description: |-
                  Protocol for port. Must be UDP, TCP, or SCTP.
                  Defaults to "TCP".
                type: string
```
