### ISSUE TITLE
Core group can be used as "" or "core" but deduplication doesn't take that into account

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/controller-tools#1036]
### Problem statement

0.16.0 introduced deduplication in #937.

Since core can be referred to by `""` or `"core"` this should be taken into account but it isn't causing 2 apigroups to be added for the same core group.

### How to reproduce

Have 2 different but logically identical codemarkers:

```
//+kubebuilder:rbac:groups=core,resources=events,verbs=create;patch
```

and 

```
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch
```

Get the following generated with 0.16.1:

```
rules:
- apiGroups:
  - ""
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
```

The workaround is to use the same apigroup everywhere.
