### ISSUE TITLE
Format validation key specified for string typed field is being ignored

### ISSUE THREAD

**Issue by sslavic** [kubernetes-sigs/controller-tools#123]
Following http://kubebuilder.netlify.com/beyond_basics/generating_crd.html#validation I tried to specify Format validation key for a string typed field e.g.
```
	// +kubebuilder:validation:Format=hostname
	Hostname string `json:"hostname"`
```
Generated CRD validation openAPIV3Schema included the property but format was ignored:
```
          properties:
            hostname:
              type: string
```
I expected 
```
          properties:
            hostname:
              type: string
              format: hostname
```

Bug seems to be in https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/internal/codegen/parse/crd.go#L279
where additionally `f` should be set to `props.Format` if one is set (i.e. non-empty string).

Affected version: "v0.1.8"
