### ISSUE TITLE
Should array schema include "format" key?

### ISSUE THREAD

**Issue by alegacy** [kubernetes-sigs/controller-tools#141]
Does it make sense to include the "format" key within a schema when the type is "array"?   For example, I created an array of strings and wanted those strings to be formatted as IPv4 addresses.  After fixing #123  to ensure that "format" keys are included for strings I found that the "format" key was included in both the array definition and the "items" definitions.   I cannot think of a reason why the outer format would be required.

With this in my types.go struct:

```
	// +kubebuilder:validation:Format=ipv4
	// list of IP addresses
	Addresses []string `json:"addresses,omitempty"`
```

I get this in my CRD yaml (notice the "format: ipv4" at both the array and items levels).  I am proposing to remove the one at the array level unless there is a reason for this that I have not yet uncovered:

```
        spec:
          properties:
            addresses:
              description: list of IP addresses
              format: ipv4
              items:
                format: ipv4
                type: string
              type: array
```
