### ISSUE TITLE
 quote escaping doesn't work properly in JsonPath for additionalPrinterColumn annotation

### ISSUE THREAD

**Issue by sohankunkerkar** [kubernetes-sigs/controller-tools#178]
**What happened:**
Quote escaping expression does not work as expected in Jsonpath for`additionalPrinterColumns` feature.

**What you expected to happen:**
It should handle the quote escaping expression

**How to reproduce it (as minimally and precisely as possible):**
you can use the below annotation for a given API type
`// +kubebuilder:printcolumn:name="ready",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status"`
With the above annotation, it genrates the following CRD:
```yaml
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type==\"Ready\")].status
    name: ready
    type: string
```
and if you use `kubectl`, it will print the information shown below:
```
$ kubectl get federatedclusters -n federation-system
NAME       
cluster1     
cluster2   
```
Ideally, it should output the following information:
```
$ kubectl get federatedclusters -n federation-system
NAME         AGE           READY
cluster1     20m           true
cluster2     20m           true
```

**Comment by mengqiy** [comment]
@sohankunkerkar  Are you expecting the generated CRD to look like the following
```
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: ready
    type: string
```
