### ISSUE TITLE
RBAC generation results in duplicates

### ISSUE THREAD

**Issue by benjaminjb** [kubernetes-sigs/controller-tools#206]
If I have multiple files with overlapping (or even identical) annotations for rbac specifications and run `go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go rbac`, I get duplicate entries in my `rbac_role.yaml`.

Is this on purpose, to let people know how many times they have included an rbac annotation? Or should the generator dedup RBAC roles?

**Comment by benjaminjb** [comment]
I'm guessing the culprit is this append: https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/rbac/parser.go#L80

**Comment by djzager** [comment]
@benjaminjb As someone that's wanting to contribute more to the controller-tools project, but doesn't know all of the intricacies of the project, it would be really helpful to have a set of recreation steps. This way, if I attempted to fix it, I would have some way of knowing with confidence that I actually addressed the issue.

**Comment by djzager** [comment]
> I'm guessing the culprit is this append: https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/rbac/parser.go#L80

It's usually better to use a permalink in these circumstances as this line has changed in the, almost year, since this issue was created.

https://github.com/kubernetes-sigs/controller-tools/blob/35a714515c99ad819bf5c4c8252491585c3e53b5/pkg/rbac/parser.go#L80

Versus 

https://github.com/kubernetes-sigs/controller-tools/blob/d6efdcdd90e2a95ae7aea0dbec3252b705a9314d/pkg/rbac/parser.go#L80

**Comment by djzager** [comment]
I went ahead and tried to re-create this by creating two APIs:

```shell
$  kubebuilder create api --group batch --version v1 --kind CronJob
$  kubebuilder create api --group batch --version v1 --kind CronJob2
```

And updating the cronjob_controller.go to duplicate the annotations from cronjob2_controller.go:

```go
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjob2s,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjob2s/status,verbs=get;update;patch
```

ran `make manifests` and did not see duplicates in `config/rbac/role.yaml`:

```yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjob2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjob2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
```
