### ISSUE TITLE
Can't have a field named "items"

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/controller-tools#227]
I have the following schema, modeled after the [GCE API](https://cloud.google.com/compute/docs/reference/rest/v1/instances):

```go
type GceInstanceSpec struct {
	// +kubebuilder:validation:Pattern=^zones/[-a-z0-9]+/machineTypes/[-a-z0-9]+$
	MachineType string `json:"machineType"`

	// +kubebuilder:validation:Pattern=^[-a-z0-9]+$
	Project string `json:"project"`

	// +kubebuilder:validation:Pattern=^[-a-z0-9]+$
	Zone string `json:"zone"`

	Metadata InstanceMetadata `json:"metadata,omitempty"`
}

type InstanceMetadata struct {
	Items []InstanceMetadataItem `json:"items,omitempty"`  // <<<<<<<<
}

type InstanceMetadataItem struct {
	// +kubebuilder:validation:Pattern=^[-a-z0-9]+$
	Key   string `json:"key"`
	Value string `json:"value"`
}
```

The generated OpenAPI schema looks like this:

```yaml
        spec:
          properties:
            machineType:
              pattern: ^zones/[-a-z0-9]+/machineTypes/[-a-z0-9]+$
              type: string
            metadata:
              properties:
                items:
                  items:
                    properties:
                      key:
                        pattern: ^[-a-z0-9]+$
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
              type: object
            project:
              pattern: ^[-a-z0-9]+$
              type: string
            zone:
              pattern: ^[-a-z0-9]+$
              type: string
```

Note the doubling of "items", which may be causing an ambiguity. When I run a test that creates one of these, I get an error:

```
        <*errors.StatusError | 0xc000316360>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
                Status: "Failure",
                Message: "GceInstance.environments.devops.cloud.google.com \"instance-bnft\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"environments.devops.cloud.google.com/v1alpha1\", \"kind\":\"GceInstance\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-06-18T22:27:20Z\", \"finalizers\":[]interface {}{\"gce\"}, \"generation\":1, \"name\":\"instance-bnft\", \"namespace\":\"default\", \"uid\":\"3ce49911-9218-11e9-9e9a-480fcf444ab6\"}, \"spec\":map[string]interface {}{\"machineType\":\"zones/zone-5vxu/machineTypes/type-zd5h\", \"metadata\":map[string]interface {}{\"items\":[]interface {}{map[string]interface {}{\"key\":\"foo\", \"value\":\"bar\"}, map[string]interface {}{\"key\":\"baz\", \"value\":\"qux\"}}}, \"project\":\"project-oaiv\", \"zone\":\"zone-5vxu\"}, \"status\":map[string]interface {}{}}: validation failure list:\ntype in spec.metadata is required",
                Reason: "Invalid",
                Details: {
                    Name: "instance-bnft",
                    Group: "environments.devops.cloud.google.com",
                    Kind: "GceInstance",
                    UID: "",
                    Causes: [
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: map[string]interface {}{\"apiVersion\":\"environments.devops.cloud.google.com/v1alpha1\", \"kind\":\"GceInstance\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-06-18T22:27:20Z\", \"finalizers\":[]interface {}{\"gce\"}, \"generation\":1, \"name\":\"instance-bnft\", \"namespace\":\"default\", \"uid\":\"3ce49911-9218-11e9-9e9a-480fcf444ab6\"}, \"spec\":map[string]interface {}{\"machineType\":\"zones/zone-5vxu/machineTypes/type-zd5h\", \"metadata\":map[string]interface {}{\"items\":[]interface {}{map[string]interface {}{\"key\":\"foo\", \"value\":\"bar\"}, map[string]interface {}{\"key\":\"baz\", \"value\":\"qux\"}}}, \"project\":\"project-oaiv\", \"zone\":\"zone-5vxu\"}, \"status\":map[string]interface {}{}}: validation failure list:\ntype in spec.metadata is required",
                            Field: "[]",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 422,
            },
        }
        GceInstance.environments.devops.cloud.google.com "instance-bnft" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"environments.devops.cloud.google.com/v1alpha1", "kind":"GceInstance", "metadata":map[string]interface {}{"creationTimestamp":"2019-06-18T22:27:20Z", "finalizers":[]interface {}{"gce"}, "generation":1, "name":"instance-bnft", "namespace":"default", "uid":"3ce49911-9218-11e9-9e9a-480fcf444ab6"}, "spec":map[string]interface {}{"machineType":"zones/zone-5vxu/machineTypes/type-zd5h", "metadata":map[string]interface {}{"items":[]interface {}{map[string]interface {}{"key":"foo", "value":"bar"}, map[string]interface {}{"key":"baz", "value":"qux"}}}, "project":"project-oaiv", "zone":"zone-5vxu"}, "status":map[string]interface {}{}}: validation failure list:
        type in spec.metadata is required

```

The error goes away if I change the json tag from "items" to "items_".

**Comment by ekuefler** [comment]
/remove-lifecycle stale

I believe this is still an issue.

**Comment by ekuefler** [comment]
/remove-lifecycle stale

Still sad about this

**Comment by djzager** [comment]
Played around with this a little bit and it is definitely still an issue. Was able to recreate it by starting up the trivial CronJob example from the kubebuilder book, updating the CronJobSpec to look like the original comment, creating a test that created the CronJob, and it failed similarly.

Additionally, I wanted to see what would happen if I simply applied the generated CRD and created the instance (without the client) using `kubectl`.

Obligatory version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

The `CronJob` I had specified in my recreator:

```go
			cronJob := &batchv1.CronJob{
				ObjectMeta: kmetav1.ObjectMeta{
					Name:      "example-cronjob",
					Namespace: "testns",
				},
				Spec: batchv1.CronJobSpec{
					Metadata: batchv1.InstanceMetadata{
						Items: []batchv1.InstanceMetadataItem{
							batchv1.InstanceMetadataItem{
								Key:   "key1",
								Value: "value1",
							},
							batchv1.InstanceMetadataItem{
								Key:   "key2",
								Value: "value2",
							},
						},
					},
				},
			}
```

The validation section of my `CronJob` CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
...
  validation:
    openAPIV3Schema:
      description: CronJob is the Schema for the cronjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CronJobSpec defines the desired state of CronJob
          properties:
            foo:
              description: Foo is an example field of CronJob. Edit CronJob_types.go
                to remove/update
              type: string
            metadata:
              properties:
                items:
                  items:
                    properties:
                      key:
                        pattern: ^[-a-z0-9]+$
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
              type: object
          type: object
        status:
          description: CronJobStatus defines the observed state of CronJob
          type: object
      type: object
```

My sample `CronJob` yaml:

```yaml
apiVersion: batch.tutorial.kubebuilder.io/v1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  metadata:
    items:
      - key: "key1"
        value: "value1"
      - key: "key2"
        value: "value2"
```

And it worked as expected:

```
$ kubectl get cronjobs.batch.tutorial.kubebuilder.io cronjob-sample -o yaml
apiVersion: batch.tutorial.kubebuilder.io/v1
kind: CronJob
metadata:
  creationTimestamp: "2020-03-05T09:36:30Z"
  generation: 1
  name: cronjob-sample
  namespace: default
  resourceVersion: "2802"
  selfLink: /apis/batch.tutorial.kubebuilder.io/v1/namespaces/default/cronjobs/cronjob-sample
  uid: 67f26943-5a4e-485f-babc-2e72f2a2cac0
spec:
  metadata:
    items:
    - key: key1
      value: value1
    - key: key2
      value: value2
```
