### ISSUE TITLE
additionalPrinterColumns is not working as provided in example.

### ISSUE THREAD

**Issue by gautamkmr** [kubernetes-sigs/controller-tools#243]
**File** ```api/v1/cronjob_types.go ```

```
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Hello",type="date",JSONPath=".metadata.creationTimestamp"

// CronJob is the Schema for the cronjobs API
type CronJob struct {
        /*
         */
        metav1.TypeMeta   `json:",inline"`
        metav1.ObjectMeta `json:"metadata,omitempty"`

        Spec   CronJobSpec   `json:"spec,omitempty"`
        Status CronJobStatus `json:"status,omitempty"`
}
```

**Generated CRD** ``` config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml ```

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: cronjobs.batch.tutorial.kubebuilder.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Hello
    type: date
  group: batch.tutorial.kubebuilder.io
  names:
    kind: CronJob
    plural: cronjobs
  scope: ""
  subresources:
  ....
````

However the out put still doesn't show that `Hello` column
```
88e9fe562973:project gauta$ k get cronjobs.batch.tutorial.kubebuilder.io
NAME             AGE
cronjob-sample   5s
```
