### ISSUE TITLE
Spec of API machinery's Quantity is wrong (incomplete)

### ISSUE THREAD

**Issue by sttts** [kubernetes-sigs/controller-tools#328]
https://github.com/kubernetes-sigs/controller-tools/blob/538d4b23662f14d691b7c4c3a9a841a497a4f1e2/pkg/crd/known_types.go#L58 specifies quantities as string, while they allow ints and numbers https://github.com/kubernetes/kubernetes/blob/5713c22eecff4610026643fbd3d37c33a43c168d/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity_test.go#L219. We cannot express int-or-number-or-string in structural schemas, but we have `x-kubernetes-int-or-string`. That would make the spec more complete than today.

**Comment by DirectXMan12** [comment]
huh?

The code in k8s.io/apimachinery says otherwise: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L393

**Comment by sttts** [comment]
Isn't https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L646 the relevant line? Quotes are optional. The OpenAPI spec you link to is incomplete (OpenAPI v2 ...).

**Comment by DirectXMan12** [comment]
Interesting... was that intended?  Generally our OpenAPI is less restrictive that what we accept (i.e. we validate more than what our OpenAPI says), but in this case the OpenAPI is *more* restrictive that what we accept.

**Comment by DirectXMan12** [comment]
Technically, neither is right (it should be `int or (string that matches the quantity format)`), but I guess since we accept raw integers in the parsing logic we can move forward with that.

**Comment by sttts** [comment]
IMO the v2 spec is just wrong. A published spec should never be too restrictive. It may be incomplete server side validation will do the final check anyway.

I agree, we could add a regex to specify `string that matches the quantity format` if we want to. Maybe we actually should to avoid unmarshalling errors in Go code.

**Comment by dthomson25** [comment]
@sttts and @DirectXMan12, isn't it true that a quantity can be float (i.e. 1.2 not "1.2")? If that's the case, then isn't a stringOrInt is too restrictive?

**Comment by DirectXMan12** [comment]
I *think* when you specify a decimal, it needs to be in quotes, otherwise other systems will parse it as a float, voiding the entire purpose of resource.Quantity.  `UnmarshalJSON` technically accepts unqualified floats (like it accepts unqualified ints), but I'd *guess* that's probably a bug.

@sttts thoughts?

**Comment by jessesuen** [comment]
> I think when you specify a decimal, it needs to be in quotes

You can specify decimal without quotes. The following valid:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 0.5
...
```

The normalized version of `0.5` cpu eventually becomes `"500m"`.

In our CRD, when generating the OpenAPI validation spec for a field which is of `resource.Quantity`, controller-tools **_incorrectly_** generates:

```yaml
properties:	
limits:	
  additionalProperties:	
    anyOf:	
    - type: integer	
    - type: string	
    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$	
    x-kubernetes-int-or-string: true	
  type: object	
requests:	
  additionalProperties:	
    anyOf:	
    - type: integer	
    - type: string	
    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$	
    x-kubernetes-int-or-string: true	
  type: object	
```

Which does not allow decimals. To work around this, we currently have to surgically remove the `resource.Quantity` validation.
