### ISSUE TITLE
Support validating internal list items on list types

### ISSUE THREAD

**Issue by robbie-demuth** [kubernetes-sigs/controller-tools#342]
Per https://book.kubebuilder.io/reference/markers/crd-validation.html, validating tags like `+kubebuilder:validation:MinLength` and `kubebuilder:validation:Pattern` must be specified on `string` fields or `string` types. If one has a field of type `[]string`, however, it is impossible to use such tags on the field directly to enforce validation on the individual list items. This forces users to alias the list item type and place the validation on the type itself like so:

```go
// +kubebuilder:validation:MinLength=1
type NonEmptyString string

// +k8s:openapi-gen=true
type CRSpec struct {
  Field []NonEmptyString `json:"field"`
}
```

This leads to undesired consequences like having to export the type so that it can be referenced in controller packages and having to cast list items since there is no easy way to cast `[]NonEmptyString` to `[]string`.

It used to previously be possible to add the validation tag to the field itself like so:

```go
// +k8s:openapi-gen=true
type CRSpec struct {
  // +kubebuilder:validation:MinLength=1
  Field []string `json:"field"`
}
```

Doing so, however, would generate the following CRD where the validation was present on both the list itself as well as its items:

```yaml
field:
  items:
    minLength: 1
    type: string
  minLength: 1
  type: array
```

Now, the CRD is generated as follows:

```yaml
field:
  items:
    type: string
  type: array
```

It'd be great if the validating tags could be specified on the field itself and result in the following CRD:

```yaml
field:
  items:
    minLength: 1
    type: string
  type: array
```

Previously, I was using `v0.9.0` of the Operator SDK which used `controller-tools` `v0.1.11-0.20190411181648-9d55346c2bde`. Now, I'm using `v0.11.0` of the Operator SDK which uses `controller-tools` `v0.2.0`
