### ISSUE TITLE
singular annotation does not get apply to the crd

### ISSUE THREAD

**Issue by danigrmartinez** [kubernetes-sigs/controller-tools#343]
I wanted to get a specific single and plural name not base on the kind of the CRD. According to the [documentation](https://book.kubebuilder.io/reference/markers/crd.html) can be done using the `+kubebuilder:resource:singular`.

### Reproduce the issue
```
// +kubebuilder:resource:singular=my-singular,path=my-plural,scope=namespaced
```

### Expected CRD result
```
  group: group.com
  names:
    kind: MyKindType
    listKind: MyKindTypeList
    plural: my-plural
    singular: my-singular
  scope: namespaced
```

### Actual CRD result
```
  group: group.com
  names:
    kind: MyKindType
    listKind: MyKindTypeList
    plural: my-plural
    singular: mykindtype
  scope: namespaced
```

This is because on the [ApplyToCRD function](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/markers/crd.go#L298-L313), Singular filed is not use.

I saw some comments about singular but I couldn't understand if it is intentional ignore or it was just forgot.
Thanks!
