### ISSUE TITLE
Generate labels requirements

### ISSUE THREAD

**Issue by Kyrremann** [kubernetes-sigs/controller-tools#370]
In our CRD we require that everyone labels their resource with a `team`-label. In `openAPIV3Schema` we can use the following:
```
metadata:
  type: object
  required:
    - labels
  properties:
    labels:
      required:
        - team
      properties:
        team:
          type: string
```

But I can't seem to find a way to solve this with the `controller-gen` tool.

Has anyone tried to do something similar, or is this maybe an unsupported feature?
