### ISSUE TITLE
Client-side validation fails with kubectl versions 1.14 and below

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/controller-tools#392]
For the field typed `IntOrString`, controller-tools started to generate a type information in CRD like the following:
```
maxUnavailable:
  anyOf:
  - type: integer
  - type: string
  x-kubernetes-int-or-string: true
```

This type information in CRD is not recognized by kubectl versions 1.14 and below. It looks like support has been added in 1.15, see https://github.com/kubernetes/kubernetes/pull/78815
