### ISSUE TITLE
Failed to create webhook configuration with v0.2.7 

### ISSUE THREAD

**Issue by binoue** [kubernetes-sigs/controller-tools#417]
**What happened**:

I updated controller-tools from v0.2.5 to v0.2.7 and generated our manifests from the source code scaffolded by `kubebuilder`.
The generated webhook manifests were like below and not properly generated.

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig: {}
  name: ""
...
```
After adding `matchPolicy="Equivalent"` marker, the manifest was properly generated.
Based on [this code](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L63), specifying `matchpolicy` is optional and this behavior looks like a bug. 

**What you expected to happen**:

I expected the generated manifests are the same as that by controller-tools v0.2.5

**Solution**:
Add the codes like below to handle the case where `matchpolicy` marker is not set.

```diff
--- a/pkg/webhook/parser.go
+++ b/pkg/webhook/parser.go
@@ -194,6 +194,8 @@ func (c Config) matchPolicy() (*admissionreg.MatchPolicyType, error) {
                matchPolicy = admissionreg.Exact
        case strings.ToLower(string(admissionreg.Equivalent)):
                matchPolicy = admissionreg.Equivalent
+       case "":
+               return nil, nil
        default:
                return nil, fmt.Errorf("unknown value %q for matchPolicy", c.MatchPolicy)
```
