### ISSUE TITLE
CRD marker `kubebuilder:unservedversion` not working

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/controller-tools#462]
Saw #403 

Should I expect the CRD marker `kubebuilder:unservedversion` to work in [v2.3.1](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v2.3.1)?

I have two CRD versions and would like to set one as storage version and the other unserved:
```
versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1alpha2
    served: **false**
    storage: false
```

I was able to have the storage version set on v1alpha1 by CRD marker `kubebuilder:storageversion`, but the marker `kubebuilder:unservedversion` on v1alpha2 didn't set `served=false`:
```
versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1alpha2
    served: **true**
    storage: false
```
