### ISSUE TITLE
Empty "Items" object for array in generated v1 CRD is invalid

### ISSUE THREAD

**Issue by grdryn** [kubernetes-sigs/controller-tools#477]
We've got a CRD generated by `controller-gen` that gets an empty Items object for a list/array in the yaml output. Given that this is a v1 CRD, this results in the CRD not being applicable to a cluster (k8s 1.16+ at least, it seems). It doesn't seem possible to add any markers to influence this, so I'm currently working around it by changing it after generation to have `type: object`.

Also, I'm not sure if it's related (might be why `items` is empty?), is that this type is recursive: a `Route` instance can have a `Routes` field, which is a `[]Route`.

[Here](https://github.com/grdryn/prometheus-operator/blob/b7085d3230f06d97d4da94efc3beafc6279b80d7/pkg/apis/monitoring/v1/alertmanager_config_types.go#L64)'s the type definition that the offending CRD is generated from, and [here](https://github.com/grdryn/prometheus-operator/blob/b7085d3230f06d97d4da94efc3beafc6279b80d7/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L346..L348)'s how it's generated.

This might be related to the discussion in #342 where @sttts and @DirectXMan12 talk about possibly having `:items:` markers, but I'm not sure. Maybe at a minimum it should by default be able to add the required `type: object` for this case (without needing a marker)?

**Comment by Wenfeng-GAO** [comment]
I meet the same problem, it seems that it doesn't work well for recursive struct definition.

When I apply generated crd to k8s, it prints out

```bash
The CustomResourceDefinition "daemonsets.kube-manager.karrier.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[updateStrategy].properties[priorityStrategy].properties[orderPriority].items.properties[orderPriority].items.type: Required value: must not be empty for specified array items
```

And my struct is recursive list as well:

```go
type PriorityStrategy struct {
	OrderPriority []OrderPriorityItem `json:"orderPriority,omitempty"`
}

type OrderPriorityItem struct {
	Selector      metav1.LabelSelector `json:"selector,omitempty"`
	OrderPriority []OrderPriorityItem  `json:"orderPriority,omitempty"`
}
```
generated crd is :
```yaml
                  priorityStrategy:
                    properties:
                      orderPriority:
                        items:
                          properties:
                            orderPriority:
                              items: {}
                              type: array
                            selector:
```
