### ISSUE TITLE
Specify a default value for array items.

### ISSUE THREAD

**Issue by jmencak** [kubernetes-sigs/controller-tools#491]
Consider a recursive type definition:

```
type Rec struct {
        // Some other definition here
        Rec []Rec `json:"rec"`
}
```

When generating a CRD by `cmd/controller-gen`, I'm getting `openAPIV3Schema` with:

```
              rec:
                // Some other definition here
                type: array
                items: { }
```

When trying to apply this CRD, I'm getting:

```
The CustomResourceDefinition "XYZ" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[rec].items.type: Required value: must not be empty for specified array items
```

The following, however, applies cleanly:

```
              rec:
                // Some other definition here
                type: array
                items: { type: object }
```

Would it make sense to add a default type "object" to array items?  Thank you.
