### ISSUE TITLE
envtest cannot load crd yaml as openAPIV3Schema is invalid

### ISSUE THREAD

**Issue by bluven** [kubernetes-sigs/controller-tools#506]
I was writing tests for a controller, but the tests failed all the time, as the envtest from controller-runtime could not load a CRD file. The CRD is called ImageDownload which has a status as subresources.

My CRD types:
```
// +kubebuilder:object:root=true
// +kubebuilder:resource:shortName=idl
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase",description="The phase of downloading"
// +kubebuilder:printcolumn:name="StartTime",type="date",JSONPath=".status.startTime",description="When the download started"
// +kubebuilder:printcolumn:name="EndTime",type="date",JSONPath=".status.endTime",description="When the download ended"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="The createTimestamp of download"
// ImageDownload is the Schema for the imagedownloads API
type ImageDownload struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ImageDownloadSpec   `json:"spec,omitempty"`
	Status ImageDownloadStatus `json:"status,omitempty"`
}

// ImageDownloadSpec defines the desired state of ImageDownload
type ImageDownloadSpec struct {
	// +kubebuilder:validation:Required
	Image string `json:"image,omitempty"`

	// +kubebuilder:validation:Required
	TargetEdge string `json:"targetEdge,omitempty"`
}

// ImageDownloadStatus defines the observed state of ImageDownload
type ImageDownloadStatus struct {
	Phase  DownloadStatus `json:"phase,omitempty"`
	Reason string         `json:"reason,omitempty"`

	StartTime *metav1.Time `json:"startTime,omitempty"`
	EndTime   *metav1.Time `json:"endTime,omitempty"`
}
```

Error message: 
```
CustomResourceDefinition.apiextensions.k8s.io "imagedownloads.app.bocloud.com" is invalid: spec.validation.openAPIV3Schema: Invalid value
...

must only have "properties", "required" or "description" at the root if the status subresource is enabled
```

PS: There are a lot of messages which I don't think it's necessary to show here. If you need, I will append.

The CRD file:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: imagedownloads.app.bocloud.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: The phase of downloading
    name: Phase
    type: string
  - JSONPath: .status.startTime
    description: When the download started
    name: StartTime
    type: date
  - JSONPath: .status.endTime
    description: When the download ended
    name: EndTime
    type: date
  - JSONPath: .metadata.creationTimestamp
    description: The createTimestamp of download
    name: Age
    type: date
  group: app.bocloud.com
  names:
    kind: ImageDownload
    listKind: ImageDownloadList
    plural: imagedownloads
    shortNames:
    - idl
    singular: imagedownload
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ImageDownload is the Schema for the imagedownloads API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ImageDownloadSpec defines the desired state of ImageDownload
          properties:
            image:
              type: string
            targetEdge:
              type: string
          type: object
        status:
          description: ImageDownloadStatus defines the observed state of ImageDownload
          properties:
            endTime:
              format: date-time
              type: string
            phase:
              type: string
            reason:
              type: string
            startTime:
              format: date-time
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

```

It seems the problem was caused by the field `type: Object` under `openAPIV3Schema`, and I tried to delete this line, it worked. 
So I wander how should I do to make controller-gen won't generate this line when subresources is enabled.
