### ISSUE TITLE
How to skip type "interface" ? 

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/controller-tools#519]
I searched the open issue, saw https://github.com/kubernetes-sigs/controller-tools/issues/383 is closed with no solution. So I logged a new one to track.

I have a CRD with some fields set to `interface{}`, here's an example:
````shell
type Validation struct {
	// Specifies validation pattern
	// +kubebuilder:validation:XPreserveUnknownFields
	// +optional
	Pattern interface{} `json:"pattern,omitempty" yaml:"pattern,omitempty"`

	// Specifies list of validation patterns
	// +kubebuilder:validation:XPreserveUnknownFields
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:nullable
	AnyPattern []interface{} `json:"anyPattern,omitempty" yaml:"anyPattern,omitempty"`
}
````

When I ran `controller-gen crd` it generated error `unsupported AST kind *ast.InterfaceType` on `interface{}`. Does it matter?  Is there a way to ignore the error? I do see the schema is generated: 
````yaml
                    validate:
                      description: Checks matching resources.
                      properties:
                        anyPattern:
                          description: Specifies list of validation patterns
                          items: {}
                          nullable: true
                          type: array
                          x-kubernetes-preserve-unknown-fields: true
                        pattern:
                          description: Specifies validation pattern
                          x-kubernetes-preserve-unknown-fields: true
````

However, when I apply this manifest to cluster, I got the following error:
```
spec.validation.openAPIV3Schema.properties[spec].properties[rules].items.properties[validate].properties[anyPattern].items.type: Required value: must not be empty for specified array items
```

It says `anyPattern` is required but I have this label `// +kubebuilder:validation:Optional` defined, am I missing anything?
