### ISSUE TITLE
controller-gen generates unstructural OpenAPI schema when referring to an inline struct twice

### ISSUE THREAD

**Issue by Blokje5** [kubernetes-sigs/controller-tools#558]
When embedding a struct inline within a CRD and accidentally duplicating the field (see examples) controller-gen fails to generate a structural (flattened) OpenAPI schema.

This can be reproduced with the following (contrived) examples:

Package api
```go
package api

import (
	"github.com/blokje5/controller-gen-bug-repro/api2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root:=true
// +kubebuilder:subresource:status

type Foo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FooSpec   `json:"spec"`
}


type FooSpec struct {
	// +required
	EmbeddedFooSpec api2.FooSpec `json:",inline"`

	Bars []Bar `json:"bars"`
}

type Bar struct {
	Bar api2.Bar `json:",inline"`
}
```

Package api2
```go
package api2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root:=true
// +kubebuilder:subresource:status

type Foo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FooSpec   `json:"spec"`
}


type FooSpec struct {
	Bars []Bar `json:"bars"`
}

type Bar struct {
	// Baz is a string
	Baz string `json:"baz"`
}
```

Generated schema:
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: foos.fake.blokje5.dev
spec:
  group: fake.blokje5.dev
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: api
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              bars:
                allOf:
                - items:
                    properties:
                      baz:
                        description: Baz is a string
                        type: string
                    required:
                    - baz
                    type: object
                - items:
                    properties:
                      baz:
                        description: Baz is a string
                        type: string
                    required:
                    - baz
                    type: object
                type: array
            required:
            - bars
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

```

As you can see in the example above, bars is defined in two places: In `api2.FooSpec`, which is used Inline in `api.FooSpec` and in indirectly in `api.FooSpec.Bars` as `api.Bar` embeds `api2.Bar` inline. This essentially leads to a conflict in the generated OpenAPI schema, as both fields would end up in the same position. Expected behaviour would be controller-gen reporting an error on the conflicting fields.

### Other relevant information
```bash
> controller-gen --version
Version: v0.5.0
```
