### ISSUE TITLE
How to add "PreserveUnknownFields" into additionalProperties

### ISSUE THREAD

**Issue by horis233** [kubernetes-sigs/controller-tools#562]
### Question Type:

CRD generation

### Background:

In the controller API types, we have a map of the `runtime.RawExtension`, see

```
	// Spec is the configuration map of custom resource.
	// +kubebuilder:pruning:PreserveUnknownFields
	Spec map[string]runtime.RawExtension `json:"spec"
```

Since it is raw data, in order to preserve fields in the custom resource we need to set `x-kubernetes-preserve-unknown-fields: true` in the CRD.

What I did is manually adding `x-kubernetes-preserve-unknown-fields: true` under the `additionalProperties` like:

```
                      additionalProperties:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      description: Spec is the configuration map of custom resource.
                      type: object
```

This can solve my problem, however, when I generate the CRD by `controller-gen`,   `x-kubernetes-preserve-unknown-fields: true` is removed from ` additionalProperties:`, but added under the parent field, like

```
                      additionalProperties:
                        type: object
                      description: Spec is the configuration map of custom resource.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
```

I understand it is expected, but is there a method to generate `x-Kubernetes-preserve-unknown-fields: true` under the `additionalProperties:` by `controller-go`?

 **controller-go Version:** 

v0.4.0

 **controller-go Options:** 

```
"crd:trivialVersions=true"
```
