### ISSUE TITLE
+kubebuilder:validation:Required marker not working

### ISSUE THREAD

**Issue by parthyadav3105** [kubernetes-sigs/controller-tools#599]
**What happened**
On using **+kubebuilder:validation:Required** marker on fields(or packages both) does not adds that field to `required` list in the generated crd output.

Example:
```
type ImageSpec struct {
	// +kubebuilder:validation:Required
	Foo string `json:"foo,omitempty"`
}
```
output crd:
```

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: images.hello.io.kupenstack.io
spec:
  group: hello.io.kupenstack.io
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Image is the Schema for the images API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: ImageSpec defines the desired state of Image
            properties:
              foo:
                type: string
            type: object
          status:
            description: ImageStatus defines the observed state of Image
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

```

**What you expected to happen:**
According to reference documentation `foo` field in above crd should be a required field as shown bellow:
```

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: images.hello.io.kupenstack.io
spec:
  group: hello.io.kupenstack.io
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Image is the Schema for the images API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: ImageSpec defines the desired state of Image
            properties:
              foo:
                type: string
            type: object
            required:
            - foo
          status:
            description: ImageStatus defines the observed state of Image
            type: object
        type: object
        required:
        - spec
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

**Environment:**
Controller-gen version: v0.4.1
Kubernetes version: Server Version: v1.21.4
