### ISSUE TITLE
Deduplicate RBAC rules

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-tools#612]
The deduplication of RBAC rules currently only merges verbs for tags with the same `groups` / `resources` / `resourceNames` / `urls`. It would be nice if we could generate rules without any duplicate permissions.

For example, the following tags:

```golang
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machinedeployments;machinedeployments/status;machinedeployments/finalizers,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machinedeployments;machinedeployments/finalizers,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machinedeployments,verbs=get;list;watch
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machinedeployments,verbs=get;list;watch;create;update;patch;delete
```

Result in:

```yaml
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machinedeployments/finalizers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machinedeployments/finalizers
  - machinedeployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

The last 2 have been merged because the resource is equal, the others are not.

Note: This can also be solved by splitting the tags to have a separate tag for each resource.

**Comment by alvaroaleman** [comment]
Deduplicating the rules with a nested map of apiGroup -> resource -> resourceNames -> verbs should be relatively easy.

One caveat is that maps are unordered. Then again this is only used to serialize it and the serialization does order it so probably doesn't matter?

**Comment by sbueringer** [comment]
Sounds good to me.

**Comment by sbueringer** [comment]
/reopen

Given there is a PR which seems to be semi-stale.

If it takes too long, I can take it over if necessary.

**Comment by Porges** [comment]
With the PR this simplifies down into:

```yaml
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machinedeployments/finalizers
  - machinedeployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
 ```
