### ISSUE TITLE
When generating a CRD the default values from kubebuilder markers are not applied correctly.

### ISSUE THREAD

**Issue by dan-tw** [kubernetes-sigs/controller-tools#631]
Given the following code in a mycustomresource_types.go file generated by kubebuilder and focusing on the kubebuilder marker and how default markers behave with nested objects.

`//+kubebuilder:default:={person:{}}`

```go
type MyProp struct {
	Person MySecondProp `json:"person,omitempty"`
}

type MySecondProp struct {
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

type MyCustomResourceSpec struct {
     
     .....

     //+kubebuilder:default:={person:{}}
     TheBeast MyProp `json:"theBeast,omitempty"`
}
```

In the generated CRD I get the following for default value for `Property`:
```yaml
theBeast:
                default:
                  person: null # <--------- this should be {}
                properties:
                  person:
                    properties:
                      age:
                        type: integer
                      name:
                        type: string
                    type: object
                type: object
```

The default value of person here in the CRD should be `{}` and not `null` as when I try to install the CRD:

```
spec.validation.openAPIV3Schema.properties[spec].properties[theBeast].default.person: Invalid value: "null": person in body must be of type object: "null"
```
