### ISSUE TITLE
additionalProperties is empty in CRD file

### ISSUE THREAD

**Issue by pingsutw** [kubernetes-sigs/controller-tools#633]
When I generated a CRD file, the additional properties is empty.

My struct:
```
type NodeStatus struct {
        QueuedAt             *metav1.Time  `json:"queuedAt,omitempty"`
	StartedAt            *metav1.Time  `json:"startedAt,omitempty"`
        SubNodeStatus         map[NodeID]*NodeStatus   `json:"subNodeStatus,omitempty"`
```

CRD File will look like
```
 subNodeStatus:
      additionalProperties: {}
      type: object
...
```

How do I manually set an additional property for SubNodeStatus?
