### ISSUE TITLE
Error when using json.RawMessage - string vs object

### ISSUE THREAD

**Issue by armsnyder** [kubernetes-sigs/controller-tools#637]
## Overview

Continuing from bug report #533 which was likely fixed and then resurfaced.

Using controller-gen `v0.6.2` you get an error when using `json.RawMessage` to represent unstructured fields.

(As a note, I would rather be able to use the `map[string]interface{}` type, which would make this bug a non-issue for me, see #636 😉 )

## Repro 1 - RawMessage has string type by default

```go
// BackendSpec defines the desired state of Backend
type BackendSpec struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	DeploymentTemplate json.RawMessage `json:"deploymentTemplate"`
}
```

Expected:

```yaml
spec:
  description: BackendSpec defines the desired state of Backend
  properties:
    deploymentTemplate:
      description: The template for created deployments.
      type: object
      x-kubernetes-preserve-unknown-fields: true
```

Actual:

```yaml
spec:
  description: BackendSpec defines the desired state of Backend
  properties:
    deploymentTemplate:
      description: The template for created deployments.
      format: byte
      type: string
      x-kubernetes-preserve-unknown-fields: true
```

## Repro 2 - Explicit `validation:Type=object` causes error

```go
// BackendSpec defines the desired state of Backend
type BackendSpec struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Type=object
	DeploymentTemplate json.RawMessage `json:"deploymentTemplate"`
}
```

Expected:

```yaml
spec:
  description: BackendSpec defines the desired state of Backend
  properties:
    deploymentTemplate:
      description: The template for created deployments.
      type: object
      x-kubernetes-preserve-unknown-fields: true
```

Actual (error):

```
api/v1alpha1:-: conflicting types in allOf branches in schema: string vs object
```

### Versions

controller-gen `v0.6.2`
k8s.io/apimachinery `v0.22.2`
k8s.io/client-go `v0.22.2`
sigs.k8s.io/controller-runtime `v0.10.2`
