### ISSUE TITLE
kubebuilder Failed to create CronJob V2 conversion  webhook: webhook resource already exists

### ISSUE THREAD

**Issue by ka-keung** [kubernetes-sigs/controller-tools#659]
# Version
kubebuilder: 3.3.0
go: 1.18  or 1.16 (both i had try)
k8s: v1.21.9

# Question
i had followed the book [kubebuilder](https://kubebuilder.io/) step by step deploy the v1 cronjob crd and webhook. it was successful.
but the follow chapter  [Multi-Version API](https://kubebuilder.io/multiversion-tutorial/tutorial.html#tutorial-multi-version-api) . the problem was exist. that was my step

step 1:
```
kubebuilder create api --group batch --version v2 --kind CronJob
Create Resource [y/n]
y
Create Controller [y/n]
n
```

step 2: same as book. but until webbook section [Setting up the webhooks](https://kubebuilder.io/multiversion-tutorial/webhooks.html#setting-up-the-webhooks)
```
kubebuilder create webhook --group batch --version v2 --kind CronJob --conversion
Error: failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": webhook resource already exists
```

and i had stick here for long time . and i had looked back this section many times . but i can't found any step i was missed or wrong, that's  why ????

here is my PROJECT file:

```
domain: tutorial.kubebuilder.io
layout:
- go.kubebuilder.io/v3
projectName: kubebuilder
repo: tutorial.kubebuilder.io
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/api/v1
  version: v1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
- api:
    crdVersion: v1
    namespaced: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/api/v2
  version: v2
version: "3"
```

**Comment by camilamacedo86** [comment]
You cannot scaffold twice, see the error `Error: failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": **webhook resource already exists**`
However, it might be a bug: (I cannot find the `--conversion` one)

```
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
```

I am closing this one since this repo is for the issues faced with controller-gen/controller-tools. 
Could you please open this issue against the KB project: https://github.com/kubernetes-sigs/kubebuilder/issues
