### ISSUE TITLE
Allow overriding schemas

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/controller-tools#705]
Hey folks, the Knative project has been looking to generate schema for our API types and have been looking at `controller-gen`.

What's unique about us is that we embed the [`corev1.PodSpec`](https://github.com/kubernetes/api/blob/7e99a1ef2ccdd2589e9a41f5083a95c375ada0a2/core/v1/types.go#L3050). Since the aim of our project is to reduce complexity for our developers there are some semantics/validation marked on the `PodSpec` type that don't apply to our use in Knative. For example the container name and port are no longer required as we assume HTTP workloads etc.

Generating the schema and doing overrides by hand is pretty fragile.  Incorporating additional tooling to manipulate the schemata after the fact isn't great since we're manipulating low level yaml (ie. delete field at some path) vs. thinking about types.

Thus I was wondering if `controller-tools` would be open to extending the functionality of `controller-gen` to allow modifying certain aspects of the types prior to generating the schemas.

The types of operations we want to perform are
- Remove fields we don't support (or want the user to set)
- Include additional markers for certain fields at a specific path in the object structure
- Update the description of various fields 

I was thinking we could extend `controller-gen` to:
- Accept a global flag `typeOverrides` that points to a config file 
- As we generate schemata check and apply the supplied overrides
- Include a new marker type that just drops all child properties (we would pair this with `x-kubernetes-preserve-unknown-fields` for unsupported features behind a feature flag - ie. `nodeAffinity`)

For the config file I was thinking of something along the lines of:

```yaml
k8s.io/api/core/v1.Volume:
  fieldMask:
    - Name
    - VolumeSource
  fieldOverride:
    VolumeSource:
      description: "VolumeSource is supported behind a feature flag"
k8s.io/api/core/v1.VolumeSource:
  additionalMarkers:
  # Part of a feature flag - so we want to omit the schema and preserve unknown fields
  - kubebuilder:validation:DropProperties
  - kubebuilder:pruning:PreserveUnknownFields
  fieldMask:
    - Secret
    - ConfigMap
    - Projected
    - EmptyDir
    - PersistentVolumeClaim
```

`fieldMask` - sets the allowable fields for a type
`additionalMarkers` - includes new markers to add to the type/field
`fieldOverride` is a map of field names to a nested override

The above override config would apply to `corev1.Volume` and `corev1.VolumeSource` globally.  There may also be a use case for overriding a schema more specifically in a specific part of the type tree - ie. imagine a go type were we embed `corev1.Volume` and I wanted to customize it's schema differently then above to only allow `EmptyDir` and `Secret` . I could then do something like

```yaml
my.special.package.dev.MyType:
  fieldOverride:
    Volume:
      fieldOverride:
        VolumeSource:
          description: "only emptyDir  and Secret is supported"
          fieldMask:
            - EmptyDir
            - Secret
```
