### ISSUE TITLE
Missing 'x-kubernetes-list-type=atomic' in files generated by controller-gen coming with kubebuilder v3.9.0

### ISSUE THREAD

**Issue by desmo999r** [kubernetes-sigs/controller-tools#772]
Hello,

I'm trying to generate a CRD based on the following implementation:
```
package v1alpha1

import (
        corev1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FunctionStatus defines the observed state of Function
type FunctionStatus struct {
        // INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
        // Important: Run "make" to regenerate code after modifying this file
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// Function is the Schema for the functions API
type Function struct {
        metav1.TypeMeta   `json:",inline"`
        metav1.ObjectMeta `json:"metadata,omitempty"`

        Spec   corev1.Container `json:"spec,omitempty"`
        Status FunctionStatus   `json:"status,omitempty"`
}
```

`make install` works great with `controller-gen v0.10.0` coming with `kubebuilder v3.8.0` but I get the following error when I try with `controller-gen v0.11.1` from `kubebuilder v3.9.0`:

```
make install
test -s /home/jandre/devel/golang/new/formol/bin/controller-gen && /home/jandre/devel/golang/new/formol/bin/controller-gen --version | grep -q v0.11.1 || \
GOBIN=/home/jandre/devel/golang/new/formol/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.1
/home/jandre/devel/golang/new/formol/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/jandre/devel/golang/new/formol/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "functions.formol.desmojim.fr" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
make: *** [Makefile:107: install] Error 1
```

I looked at the file generated by `controller-gen v0.11.1` in `config/crd/base`. If I had the line `spec.validation.openAPIV3Schema.properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type:atomic` which is missing then I can manually load the CRD.
There is no `spec.validation.openAPIV3Schema.properties[spec].properties[resources].properties[claims]` in the base file generated by `controller-gen v0.10.0`

```
$ minikube version 
v1.28.0
$ kubectl version -o yaml
clientVersion:
  buildDate: "2023-01-18T15:58:16Z"
  compiler: gc
  gitCommit: 8f94681cd294aa8cfd3407b8191f6c70214973a4
  gitTreeState: clean
  gitVersion: v1.26.1
  goVersion: go1.19.5
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-12T10:49:09Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/amd64
```

**Comment by catusax** [comment]
same

using corev1.PodSpec in my crd: 

```go
package v1

import (
	corev1 "k8s.io/api/core/v1"
)


type PodTemplateSpec struct {
	// +optional
	Spec corev1.PodSpec `json:"spec,omitempty"`
}

```

```
The CustomResourceDefinition "pods.xxx.xxx.com" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[containers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[ephemeralContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
make: *** [install] Error 1
```

generated crd:

```yaml
                              properties:
                                claims:
                                  description: "Claims lists the names of resources,
                                    defined in spec.resourceClaims, that are used
                                    by this container. \n This is an alpha field and
                                    requires enabling the DynamicResourceAllocation
                                    feature gate. \n This field is immutable."
                                  items:
                                    description: ResourceClaim references one entry
                                      in PodSpec.ResourceClaims.
                                    properties:
                                      name:
                                        description: Name must match the name of one
                                          entry in pod.spec.resourceClaims of the
                                          Pod where this field is used. It makes that
                                          resource available inside a container.
                                        type: string
                                    required:
                                    - name
                                    type: object
                                  type: array
                                  x-kubernetes-list-type: set
```


add a comment `// +mapType=atomic` on top of `ResourceClaim` struct solves this problem, but i cant edit k8s sourcecode, and others struct not having this comment are working well, so i guss this is a controller-gen's bug

**Comment by catusax** [comment]
currently,rollback to  `k8s.io/api v0.25.0` can avoid this problem

go.mod:
```
replace (
	k8s.io/api => k8s.io/api v0.25.0
	k8s.io/apimachinery => k8s.io/apimachinery v0.25.0
	k8s.io/client-go => k8s.io/client-go v0.25.0
)
```

**Comment by camilamacedo86** [comment]
Could you please try to check this scenario with the latest releases by bumping controller-gen v0.11.2 and controller-runtime 0.14.2 and k8s 0.26.1 to see if this problem would still be faced?

**Comment by desmo999r** [comment]
I gave a try to controller-gen v0.11.2, controller-runtime 0.14.2 and k8s 0.26.1.

I managed to load the generated CRD into my k8s cluster.

generated CRD:
```yaml
              resources:
                description: 'Compute Resources required by this container. Cannot
                  be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                properties:
                  claims:
                    description: "Claims lists the names of resources, defined in
                      spec.resourceClaims, that are used by this container. \n This
                      is an alpha field and requires enabling the DynamicResourceAllocation
                      feature gate. \n This field is immutable."
                    items:
                      description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                      properties:
                        name:
                          description: Name must match the name of one entry in pod.spec.resourceClaims
                            of the Pod where this field is used. It makes that resource
                            available inside a container.
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                    x-kubernetes-list-map-keys:
                    - name
                    x-kubernetes-list-type: map
```
