### ISSUE TITLE
support for setting title field of schema

### ISSUE THREAD

**Issue by utkarsh-naik** [kubernetes-sigs/controller-tools#796]
How to set the title field of schema in generated manifests. This is a specific requirement for title , in general how to set all the supported fields of schema (Open api )

The particular problem here is for creating java client using open api generator and using in line schema name mapping to set the schema name using the title field for the schema
https://openapi-generator.tech/docs/customization/#inline-schema-naming

eg -
consider below struct

```
type myStatus struct {
	Id string `json:"id,omitempty"`
	myValue MyValue `json:"val,omitempty"`
}

type MyValue struct{
       strVal string `json:"str,omitempty"`
       intVal string `json:"int,omitempty"`
}
```

this will translate to manifest as below

```
status:
  properties:
    id:
      type: string
    val:
      properties:
        str:
          type: string
        int:
          type: string
      type: object
  type: object
```

How to add title field to 'val' object like below  - 
```
status:
  properties:
    id:
      type: string
    val:
      title: MyVal
      properties:
        str:
          type: string
        int:
          type: string
      type: object
  type: object
```
