### ISSUE TITLE
must apply listType to an array, found string

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/controller-tools#907]
For `[]byte` type field:

```
// +listType=atomic
fieldA []byte `json:"fieldA,omitempty"`
```

When running controller-gen, error emits as `must apply listType to an array, found string`, this is caused by 
https://github.com/kubernetes-sigs/controller-tools/blob/4c82505401a33c8241baa64c859034bf3259eeb2/pkg/crd/markers/topology.go#L110-L113

Because the type is string right now.

```
fieldA:
    description: |-
    format: byte
    type: string
```

Any suggestions?

/kind bug
