### ISSUE TITLE
controller-gen is not consistently picking up kubebuilder:default marker

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/controller-tools#967]
On controller-gen v0.13.0, I am observing that some types (I can't quite put my finger on it) don't have `kubebuilder:default` marker set to default the object to empty object (`{}`) honored. 

I have a fairly simple repro below that sets `//+kubebuilder:default:={}` on the root  level object's `status` field.

<details>

<summary><code>type Car struct { ...</code></summary>

```go
// +groupName=example.com
// +kubebuilder:object:generate=true
// +kubebuilder:validation:Required
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "example.com", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:resource:scope=Cluster

type Car struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CarSpec `json:"spec"`

	// +kubebuilder:default:={}
	Status CarStatus `json:"status,omitempty"`
}

type CarSpec struct{}

// +kubebuilder:validation:Enum=automatic;manual
type GearType string

type CarStatus struct {
	// +kubebuilder:default:=automatic
	Gear GearType `json:"name"`
}

//+kubebuilder:object:root=true

type CarList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Car `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Car{}, &CarList{})
}
```

</details>

The generated CRD **does not have** a `status` field that has a `default: {}` field:

```yaml
          status:
            default: {}
```

<details>
<summary>generated CRD</summary>

```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: cars.example.com
spec:
  group: example.com
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            properties:
              name:
                default: automatic
                enum:
                - automatic
                - manual
                type: string
            required:
            - name
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
</details>

It's deterministic behavior, but I can't tell why the exact some marker on exact same field works on some types and not the others. 😭  Another type I have actually gets `spec.validation.openAPIV3Schema.properties[status].default` field populated.

/kind bug
/lifecycle frozen
